apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-con
        image: ashwani2399/grafana:v1
        volumeMounts:
        - name: grafana-pvc
          mountPath: /var/lib/grafana/
      volumes:
      - name: grafana-pvc
        persistentVolumeClaim:
          claimName: grafana-persistent-volume
