apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persistent-volume
  labels:
    app: grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 

